### PR TITLE
Remove missing %files in ldm.spec.in. Add runtime

### PR DESCRIPTION
**Pull request by NaderCHASER**
* Fixes “rpmbuild” errors caused by %files entries for files which no longer exist.
* Adds “runtime” to %files to fix an error which prevented “rpmbuild” from completing.

### CODE REVIEW

**Comment by semmerson** [comment]
@NaderCHASER Because this is for an RPM distribution, I think it should include the NOAAPort stuff. Most user's won't use it -- but they can't unless it's there.

Can you modify what you've done to include the NOAAPort stuff, test it, and submit another pull request?

**Comment by NaderCHASER** [comment]
I'll see what I can do.

Despite the '--with-noaaport' configure option being in ldm.spec.in, my ~/rpmbuild/BUILDROOT/ does NOT contain NOAAPort docs under /share/docs/. This causes the "rpmbuild" to fail because the files are expected (%files) but not found.

**Comment by NaderCHASER** [comment]
My dish, which runs LDM 6.13.5, doesn't have the folder /share/doc/ldm/noaaport/ either. Can you check into this @semmerson?

**Comment by semmerson** [comment]
@NaderCHASER That directory should be `/share/doc/ldm/utilities/noaaport/`. Do a `git pull` and you should be OK.

**Comment by NaderCHASER** [comment]
Tested.

`Wrote: /home/ldm/rpmbuild/RPMS/x86_64/ldm-6.13.5-1.el7.centos.x86_64.rpm
Wrote: /home/ldm/rpmbuild/RPMS/x86_64/ldm-debuginfo-6.13.5-1.el7.centos.x86_64.rpm`

**Comment by semmerson** [comment]
Excellent! Your changes have been merged.

**Pull request merged**
