### PR TITLE
NWS feature rollup 8/23/2016

### PR DESCRIPTION
**Pull request by brian-m-rapp**
New NWS features:

- fileIngester program in fileIngest/ sub-dir.  Builds with 'configure --with-ingester'.
- add capability to pqact to strip headers using Pattern-Action Rule "-removewmo".

Code has been scanned with Coverity.

### CODE REVIEW

**Comment by semmerson** [comment]
Working on it.

**Comment by semmerson** [comment]
@brian-m-rapp I notice that `productMaker.c` defines `RETRANS_SUPPORT` on line 6. This would seem to have consequences for non-NOAA users of NOAAPort: it would cause them to execute a lot of irrelevant code. Is that code guaranteed to work for non-NOAA sites? Is it meaningful for non-NOAA sites to execute that code?

**Comment by brian-m-rapp** [comment]
whoops...I put that in there temporarily and forgot to take it out once I
was done.  That *definitely* should not be there.  Good catch.

Brian

**Comment by semmerson** [comment]
Merged most modifications (some mods were obviated by subsequent changes).

**Comment by brian-m-rapp** [comment]
Excellent, Thanks Steve!

Brian

**Pull request closed without merging**
